document.addEventListener('DOMContentLoaded', () => {
    const germanWords = [
        { german: "Hund", english: "Dog" },
        { german: "Katze", english: "Cat" },
        { german: "Haus", english: "House" },
        { german: "Auto", english: "Car" },
        { german: "Baum", english: "Tree" },
        { german: "Wasser", english: "Water" },
        { german: "Buch", english: "Book" },
        { german: "Stuhl", english: "Chair" },
        { german: "Tisch", english: "Table" },
        { german: "Fenster", english: "Window" },
        { german: "Tür", english: "Door" },
        { german: "Schule", english: "School" },
        { german: "Stadt", english: "City" },
        { german: "Land", english: "Country" },
        { german: "Fluss", english: "River" },
        { german: "Berg", english: "Mountain" },
        { german: "Sonne", english: "Sun" },
        { german: "Mond", english: "Moon" },
        { german: "Stern", english: "Star" },
        { german: "Blume", english: "Flower" },
        { german: "Apfel", english: "Apple" },
        { german: "Brot", english: "Bread" },
        { german: "Milch", english: "Milk" },
        { german: "Kaffee", english: "Coffee" },
        { german: "Tee", english: "Tea" },
        { german: "Zucker", english: "Sugar" },
        { german: "Salz", english: "Salt" },
        { german: "Pfeffer", english: "Pepper" },
        { german: "Butter", english: "Butter" },
        { german: "Käse", english: "Cheese" },
        { german: "Fisch", english: "Fish" },
        { german: "Fleisch", english: "Meat" },
        { german: "Gemüse", english: "Vegetable" },
        { german: "Obst", english: "Fruit" },
        { german: "Kartoffel", english: "Potato" },
        { german: "Tomate", english: "Tomato" },
        { german: "Gurke", english: "Cucumber" },
        { german: "Karotte", english: "Carrot" },
        { german: "Zwiebel", english: "Onion" },
        { german: "Schokolade", english: "Chocolate" },
        { german: "Ei", english: "Egg" },
        { german: "Huhn", english: "Chicken" },
        { german: "Reis", english: "Rice" },
        { german: "Nudel", english: "Noodle" },
        { german: "Salat", english: "Salad" },
        { german: "Kuchen", english: "Cake" },
        { german: "Bier", english: "Beer" },
        { german: "Wein", english: "Wine" },
        { german: "Saft", english: "Juice" },
        { german: "Wald", english: "Forest" },
        { german: "Meer", english: "Sea" },
        { german: "See", english: "Lake" },
        { german: "Wiese", english: "Meadow" },
        { german: "Himmel", english: "Sky" },
        { german: "Wolke", english: "Cloud" },
        { german: "Regen", english: "Rain" },
        { german: "Schnee", english: "Snow" },
        { german: "Wind", english: "Wind" },
        { german: "Sturm", english: "Storm" },
        { german: "Feuer", english: "Fire" },
        { german: "Erde", english: "Earth" },
        { german: "Luft", english: "Air" },
        { german: "Straße", english: "Street" },
        { german: "Fahrrad", english: "Bicycle" },
        { german: "Zug", english: "Train" },
        { german: "Flugzeug", english: "Airplane" },
        { german: "Schiff", english: "Ship" },
        { german: "Boot", english: "Boat" },
        { german: "Bus", english: "Bus" },
        { german: "Taxi", english: "Taxi" },
        { german: "U-Bahn", english: "Subway" },
        { german: "Flughafen", english: "Airport" },
        { german: "Bahnhof", english: "Train station" },
        { german: "Hotel", english: "Hotel" },
        { german: "Restaurant", english: "Restaurant" },
        { german: "Café", english: "Café" },
        { german: "Supermarkt", english: "Supermarket" },
        { german: "Bäckerei", english: "Bakery" },
        { german: "Apotheke", english: "Pharmacy" },
        { german: "Krankenhaus", english: "Hospital" },
        { german: "Polizei", english: "Police" },
        { german: "Feuerwehr", english: "Fire department" },
        { german: "Post", english: "Post office" },
        { german: "Bank", english: "Bank" },
        { german: "Bibliothek", english: "Library" },
        { german: "Museum", english: "Museum" },
        { german: "Kino", english: "Cinema" },
        { german: "Theater", english: "Theater" },
        { german: "Park", english: "Park" },
        { german: "Spielplatz", english: "Playground" },
        { german: "Zoo", english: "Zoo" },
        { german: "Garten", english: "Garden" },
        { german: "Kirche", english: "Church" },
        { german: "Schloss", english: "Castle" },
        { german: "Brücke", english: "Bridge" },
        { german: "Tunnel", english: "Tunnel" },
        { german: "Turm", english: "Tower" },
        { german: "Dorf", english: "Village" }
    ];

    const cardContainer = document.querySelector('.card-container');
    cardContainer.innerHTML = germanWords.map(word => `
        <div class="card" onclick="showTranslation(this)">
            <p class="german-word">${word.german}</p>
            <p class="english-translation">${word.english}</p>
        </div>
    `).join('');

    window.showTranslation = function(card) {
        card.classList.toggle('show');
    };
});